
export const MODALITY = [
    { label: 'Chamamento Público', value: 'Chamamento Público' },
    { label: 'Regime de Contratação Estatal por Menor Preço', value: 'Regime de Contratação Estatal por Menor Preço' },
    { label: 'Concorrência por Técnica', value: 'Concorrência por Técnica' },
    { label: 'Concorrência Maior Preço', value: 'Concorrência Maior Preço' },
    { label: 'Credenciamento', value: 'Credenciamento' },
    { label: 'Chamamento Público por Técnica e Preço', value: 'Chamamento Público por Técnica e Preço' },
    { label: 'Pré-qualificação', value: 'Pré-qualificação' },
    { label: 'Chamada Pública', value: 'Chamada Pública' },
    { label: 'Registro de Preços Eletrônico por Maior Desconto', value: 'Registro de Preços Eletrônico por Maior Desconto' },
    { label: 'Dispensa Presencial', value: 'Dispensa Presencial' },
    { label: 'Registro de Preços Eletrônico', value: 'Registro de Preços Eletrônico' },
    { label: 'Dispensa Eletrônica', value: 'Dispensa Eletrônica' },
    { label: 'Pregão por Maior Desconto Eletrônico', value: 'Pregão por Maior Desconto Eletrônico' },
    { label: 'Pregão Presencial', value: 'Pregão Presencial' },
    { label: 'Pregão Eletrônico', value: 'Pregão Eletrônico' },
    { label: 'Leilão Eletrônico', value: 'Leilão Eletrônico' },
    { label: 'Concorrência por Maior Desconto', value: 'Concorrência por Maior Desconto' },
    { label: 'Concorrência por Técnica e Preço', value: 'Concorrência por Técnica e Preço' },
    { label: 'Pregão por Maior Preço', value: 'Pregão por Maior Preço' },
    { label: 'Concorrência por Menor Preço', value: 'Concorrência por Menor Preço' },
];